### ISSUE TITLE
TypeError: AggregateError is not a constructor

### ISSUE THREAD

**Issue by ggarcia24** [iamludal/semantic-release-jira-notes#7]
Hello!

First let me thank you for this amazing plugin! 🤩, I was trying to configure semantic-release with a Java repository and, was trying to test this plugin but I encountered an error:

```text
[6:19:26 PM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: AggregateError is not a constructor
    at verifyConditions (REDACTED/node_modules/semantic-release-jira-notes/src/lib/verify-conditions.js:30:11)
    at async validator (REDACTED/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async REDACTED/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (REDACTED/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
  pluginName: 'semantic-release-jira-notes'
}
AggregateError: 
    TypeError: AggregateError is not a constructor
        at verifyConditions (REDACTED/node_modules/semantic-release-jira-notes/src/lib/verify-conditions.js:30:11)
```

This is my package.json:
```json
{
  "name": "REDACTED",
  "version": "1.0.0",
  "scripts": {
    "semantic-release": "semantic-release"
  },
  "devDependencies": {
    "@commitlint/cli": "^19.5.0",
    "@semantic-release/changelog": "^6.0.3",
    "@semantic-release/git": "^10.0.1",
    "aggregate-error": "^5.0.0",
    "conventional-changelog-cli": "^5.0.0",
    "semantic-release": "^24.1.2",
    "semantic-release-commits-lint": "^1.1.0",
    "semantic-release-jira-notes": "^4.0.0"
  }
}
```

And this is my .releaserc.json:
```json
{
  "debug": true,
  "plugins": [
    "@semantic-release/commit-analyzer",
    ["semantic-release-jira-notes", {
      "jiraHost": "REDACTED"
    }],
    "@semantic-release/changelog",
    "@semantic-release/git"
  ]
}
```

My best guess is that it's related to some changes over the module 'aggregate-error', as I'm not able to find `AggregateErrorPromise` class, but it might also have something to do with the migration to ESM, my main idea being that `import()` used to return a promise and now the `import AggregateErrorPromise from "aggregate-error";` (on [verify-conditions.js#L3](https://github.com/iamludal/semantic-release-jira-notes/blob/main/src/lib/verify-conditions.js#L3) is not working in the same way

I might submit a PR later to attempt to fix it! But I wanted to check first in case I was missing something

Best regards
Gonzalo G

**Comment by edwin-speer** [comment]
I have the same error. This is in a Bitbucket pipeline

+ npx semantic-release
[10:24:56 AM] [semantic-release] › ℹ  Running semantic-release version 24.2.7
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-jira-notes"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "semantic-release-jira-notes"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[10:24:56 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[10:25:25 AM] [semantic-release] › ✔  Run automated release from branch master on repository http://bitbucket.org/speer-it/cocon-fiber
[10:25:29 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[10:25:29 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-jira-notes"
[10:25:29 AM] [semantic-release] › ✘  Failed step "verifyConditions" of plugin "semantic-release-jira-notes"
[10:25:29 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[10:25:29 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[10:25:29 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[10:25:29 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[10:25:29 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[10:25:29 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[10:25:29 AM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: AggregateError is not a constructor
    at verifyConditions (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release-jira-notes/src/lib/verify-conditions.js:30:11)
    at async validator (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
  pluginName: 'semantic-release-jira-notes'
}
AggregateError: 
    TypeError: AggregateError is not a constructor
        at verifyConditions (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release-jira-notes/src/lib/verify-conditions.js:30:11)
        at async validator (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44)
    at file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
    at async pluginsConfigAccumulator.<computed> [as verifyConditions] (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/index.js:106:3)
    at async Module.default (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/index.js:278:22)
    at async default (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    TypeError: AggregateError is not a constructor
        at verifyConditions (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release-jira-notes/src/lib/verify-conditions.js:30:11)
        at async validator (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///opt/atlassian/pipelines/agent/build/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
      pluginName: 'semantic-release-jira-notes'
    }
  ]
2025-08-18T10:25:29.556770059Z stderr P }

**Comment by iamludal** [comment]
Hey, thanks for reporting the error! If should have been fixed in the latest release, feel free to let me know if not.
