### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by malingxin** [iamludal/semantic-release-jira-notes#9]
maybe need to update changelog version
[[RangeError: Invalid time value](https://github.com/conventional-changelog/conventional-changelog/issues/1267#top)](https://github.com/semantic-release/release-notes-generator/issues/633)
```
[9:15:59 AM] [semantic-release] › ✘  Failed step "generateNotes" of plugin "semantic-release-jira-notes"
[9:15:59 AM] [semantic-release] › ✘  An error occurred while running semantic-release: RangeError: Invalid time value
    at committerDate (/opt/app/node_modules/conventional-changelog-writer/index.js:80:30)
    at /opt/app/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/opt/app/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /opt/app/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: 'semantic-release-jira-notes'
}
RangeError: Invalid time value
    at committerDate (/opt/app/node_modules/conventional-changelog-writer/index.js:80:30)
    at /opt/app/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/opt/app/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /opt/app/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: 'semantic-release-jira-notes'
}
```
release.config.js
```
    ["semantic-release-jira-notes", {
      "jiraHost": "xxxx",
      "preset": "conventionalcommits",
      "parserOpts": {
        "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING"]
      },
      "writerOpts": {
        commitPartial: readFileSync(join(__dirname, './commit.hbs'), 'utf-8')
      },
      "presetConfig": {
        "types": [
          { "type": "feat", "section": "Features" },
          { "type": "fix", "section": "Bug Fixes" },
          { "type": "perf", "section": "Performance Improvements" },
          { "type": "revert", "section": "Reverts" },
          { "type": "docs", "section": "Documentation", "hidden": true },
          { "type": "style", "section": "Styles", "hidden": true },
          { "type": "chore", "section": "Miscellaneous Chores", "hidden": true },
          { "type": "refactor", "section": "Code Refactoring", "hidden": true },
          { "type": "test", "section": "Tests", "hidden": true },
          { "type": "build", "section": "Build System", "hidden": true },
          { "type": "ci", "section": "Continuous Integration", "hidden": true },
          { "type": "improvement", "section": "Improvement", "hidden": false },
          // custom type user story
          { "type": "bug", "section": "Bug" },
          { "type": "task", "section": "Task" },
        ]
      }
    }]
```

**Comment by carlosjgp** [comment]
I'm seeing the error. It works if I change the preset to `angular`

**Comment by iamludal** [comment]
Hi, thanks for reporting the error. This should be fixed in the lates version of the plugin, feel free to let me know if it's still not working
